server:
  port: 26482

spring:
  application:
    name: cloud-document-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/${document.database-name}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包


document:
  pre-file-path: D:/document-server
  suffix-file-path-excel: .xlsx
  database-name: document
  suffix-file-path-java: .java
  next-line: "\n"
  space: " "