server:
  port: 9902

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.116.128:1111 #配置Nacos地址
        # 换成nginx的1111端口，做集群
        #server-addr: 192.168.111.144:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'


